
package com.estudos.democlientsoap.stubsv2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CountryV2Resource", targetNamespace = "http://countryv2.ws.estudos.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CountryV2Resource {


    /**
     * 
     * @param authorization
     * @param request
     * @return
     *     returns com.estudos.democlientsoap.stubsv2.CountryResponse
     */
    @WebMethod
    @WebResult(name = "country", partName = "country")
    @Action(input = "http://countryv2.ws.estudos.com/CountryV2Resource/getDetailRequest", output = "http://countryv2.ws.estudos.com/CountryV2Resource/getDetailResponse")
    public CountryResponse getDetail(
        @WebParam(name = "authorization", targetNamespace = "http://countryv2.ws.estudos.com/", header = true, partName = "authorization")
        Authentication authorization,
        @WebParam(name = "request", partName = "request")
        CountryRequest request);

}
