
package com.estudos.democlientsoap.stubsv2;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CountryV2ResourceImplService", targetNamespace = "http://resource.countryv2.ws.estudos.com/", wsdlLocation = "http://localhost:9999/ws/country/v2?wsdl")
public class CountryV2ResourceImplService
    extends Service
{

    private final static URL COUNTRYV2RESOURCEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException COUNTRYV2RESOURCEIMPLSERVICE_EXCEPTION;
    private final static QName COUNTRYV2RESOURCEIMPLSERVICE_QNAME = new QName("http://resource.countryv2.ws.estudos.com/", "CountryV2ResourceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9999/ws/country/v2?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COUNTRYV2RESOURCEIMPLSERVICE_WSDL_LOCATION = url;
        COUNTRYV2RESOURCEIMPLSERVICE_EXCEPTION = e;
    }

    public CountryV2ResourceImplService() {
        super(__getWsdlLocation(), COUNTRYV2RESOURCEIMPLSERVICE_QNAME);
    }

    public CountryV2ResourceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), COUNTRYV2RESOURCEIMPLSERVICE_QNAME, features);
    }

    public CountryV2ResourceImplService(URL wsdlLocation) {
        super(wsdlLocation, COUNTRYV2RESOURCEIMPLSERVICE_QNAME);
    }

    public CountryV2ResourceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COUNTRYV2RESOURCEIMPLSERVICE_QNAME, features);
    }

    public CountryV2ResourceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CountryV2ResourceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CountryV2Resource
     */
    @WebEndpoint(name = "CountryV2ResourceImplPort")
    public CountryV2Resource getCountryV2ResourceImplPort() {
        return super.getPort(new QName("http://resource.countryv2.ws.estudos.com/", "CountryV2ResourceImplPort"), CountryV2Resource.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CountryV2Resource
     */
    @WebEndpoint(name = "CountryV2ResourceImplPort")
    public CountryV2Resource getCountryV2ResourceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://resource.countryv2.ws.estudos.com/", "CountryV2ResourceImplPort"), CountryV2Resource.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COUNTRYV2RESOURCEIMPLSERVICE_EXCEPTION!= null) {
            throw COUNTRYV2RESOURCEIMPLSERVICE_EXCEPTION;
        }
        return COUNTRYV2RESOURCEIMPLSERVICE_WSDL_LOCATION;
    }

}
