
package com.estudos.democlientsoap.stubs;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CountryResource", targetNamespace = "http://country.ws.estudos.com/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CountryResource {


    /**
     * 
     * @param parameters
     * @param authentication
     * @return
     *     returns com.estudos.democlientsoap.stubs.GetDetailResponse
     */
    @WebMethod(action = "http://country.ws.estudos.com/getDetailSOAP")
    @WebResult(name = "getDetailResponse", targetNamespace = "http://country.ws.estudos.com/", partName = "result")
    @Action(input = "http://country.ws.estudos.com/getDetailSOAP", output = "http://country.ws.estudos.com/CountryResource/getDetailResponse")
    public GetDetailResponse getDetail(
        @WebParam(name = "getDetail", targetNamespace = "http://country.ws.estudos.com/", partName = "parameters")
        GetDetail parameters,
        @WebParam(name = "authentication", targetNamespace = "http://country.ws.estudos.com/", header = true, partName = "authentication")
        Authentication authentication);

}
