
package com.estudos.democlientsoap.stubs;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CountryResourceImplService", targetNamespace = "http://resource.country.ws.estudos.com/", wsdlLocation = "http://localhost:9999/ws/country?wsdl")
public class CountryResourceImplService
    extends Service
{

    private final static URL COUNTRYRESOURCEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException COUNTRYRESOURCEIMPLSERVICE_EXCEPTION;
    private final static QName COUNTRYRESOURCEIMPLSERVICE_QNAME = new QName("http://resource.country.ws.estudos.com/", "CountryResourceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9999/ws/country?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COUNTRYRESOURCEIMPLSERVICE_WSDL_LOCATION = url;
        COUNTRYRESOURCEIMPLSERVICE_EXCEPTION = e;
    }

    public CountryResourceImplService() {
        super(__getWsdlLocation(), COUNTRYRESOURCEIMPLSERVICE_QNAME);
    }

    public CountryResourceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), COUNTRYRESOURCEIMPLSERVICE_QNAME, features);
    }

    public CountryResourceImplService(URL wsdlLocation) {
        super(wsdlLocation, COUNTRYRESOURCEIMPLSERVICE_QNAME);
    }

    public CountryResourceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COUNTRYRESOURCEIMPLSERVICE_QNAME, features);
    }

    public CountryResourceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CountryResourceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CountryResource
     */
    @WebEndpoint(name = "CountryResourceImplPort")
    public CountryResource getCountryResourceImplPort() {
        return super.getPort(new QName("http://resource.country.ws.estudos.com/", "CountryResourceImplPort"), CountryResource.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CountryResource
     */
    @WebEndpoint(name = "CountryResourceImplPort")
    public CountryResource getCountryResourceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://resource.country.ws.estudos.com/", "CountryResourceImplPort"), CountryResource.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COUNTRYRESOURCEIMPLSERVICE_EXCEPTION!= null) {
            throw COUNTRYRESOURCEIMPLSERVICE_EXCEPTION;
        }
        return COUNTRYRESOURCEIMPLSERVICE_WSDL_LOCATION;
    }

}
